openapi: 3.0.0
info:
  title: 'My API'
  version: 1.0.0
paths:
  /api/data:
    get:
      summary: "Get Data by ID\nLogic to fetch and return data"
      operationId: getData
      responses:
        '200':
          description: 'Returns data'
  '/api/data/{id}':
    get:
      summary: "Get Data by ID\nLogic to fetch and return data"
      operationId: getDataById
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Returns data by id'
  /api/datascore:
    get:
      summary: "Get DataScore\nLogic to fetch and return data"
      operationId: getDataScore
      responses:
        '200':
          description: 'Returns dataiscore'
  '/api/datascore/{score}':
    get:
      summary: 'Get DataScore by Score'
      operationId: getDataScoreByScore
      parameters:
        -
          name: score
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Returns datascore by score'
